#pragma once

#ifndef POLOS_UTILS_PLATFORMDEFINES_H
#define POLOS_UTILS_PLATFORMDEFINES_H

#ifdef _WIN64
/* Windows x64  */
#	ifndef PL_PLATFORM_WINDOWS
#		define PL_PLATFORM_WINDOWS
#	endif // !PL_PLATFORM_WINDOWS
#endif

#endif /* POLOS_UTILS_PLATFORMDEFINES_H */

