#pragma once


#ifndef POLOS_RENDERER_RENDERERDEFINITIONS_H
#define POLOS_RENDERER_RENDERERDEFINITIONS_H

enum class render_api
{
	OPENGL,
	//VULKAN,
	//DIRECTX11,
	//DIRECTX12,
};

#endif /* POLOS_RENDERER_RENDERERDEFINITIONS_H */
