# CMAKE STUFF, YOU MAY NOT EVEN NEED THEM

# Build type categories: 
# Release
# RelWithDebInfo (Recommended when developing)
# Debug
# MinSizeRel
BUILD_TYPE=Release
BUILD_DIR=build
ENGINE_INSTALL_DIR=bin
C_COMPILER=clang
CXX_COMPILER=clang++
GENERATOR=Ninja

STATIC_STD=1
USE_OPENGL=1
USE_VULKAN=1
ENABLE_PROFILING=0
ENABLE_LOGGING=1
GUI_USE_IMGUI=1
BUILD_EDITOR=1

# You don't have to change these
BUILD_FOLDER=$BUILD_DIR/$BUILD_TYPE
INSTALL_PREFIX=$ENGINE_INSTALL_DIR/$BUILD_TYPE

#Configure cmake
cmake . -D CMAKE_BUILD_TYPE=$BUILD_TYPE \
-D CMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
-D STATIC_STD=$STATIC_STD \
-D USE_OPENGL=$USE_OPENGL \
-D USE_VULKAN=$USE_VULKAN \
-D ENABLE_PROFILING=$ENABLE_PROFILING \
-D ENABLE_LOGGING=$ENABLE_LOGGING \
-D GUI_USE_IMGUI=$GUI_USE_IMGUI \
-D BUILD_EDITOR=$BUILD_EDITOR \
-D CMAKE_EXPORT_COMPILE_COMMANDS=1 \
-G $GENERATOR \
-D CMAKE_C_COMPILER=$C_COMPILER% \
-D CMAKE_CXX_COMPILER=$CXX_COMPILER \
-B $BUILD_FOLDER

cmake --build $BUILD_FOLDER -j $(nproc) --target=install --config=$BUILD_TYPE