@echo off

REM Change below stuff with as you need

:: Build type categories: 
:: Release
:: RelWithDebInfo (Recommended when developing)
:: Debug
:: MinSizeRel
SET BUILD_TYPE=Release
SET BUILD_DIR=build
SET ENGINE_INSTALL_DIR=bin

SET /A STATIC_STD=1 & REM Should be 1 most of the time.
SET /A USE_OPENGL=1
SET /A USE_VULKAN=1
SET /A ENABLE_PROFILING=0
SET /A ENABLE_LOGGING=1
SET /A GUI_USE_IMGUI=1
SET /A BUILD_EDITOR=1


:: DONT CHANGE THESE TWO
SET BUILD_FOLDER=%BUILD_DIR%/%BUILD_TYPE%
SET INSTALL_PREFIX=%ENGINE_INSTALL_DIR%/%BUILD_TYPE%

:: Configure cmake
cmake .^
 -DCMAKE_BUILD_TYPE=%BUILD_TYPE%^
 -DCMAKE_INSTALL_PREFIX=%INSTALL_PREFIX%^
 -DSTATIC_STD=%STATIC_STD%^
 -DUSE_OPENGL=%USE_OPENGL%^
 -DUSE_VULKAN=%USE_VULKAN%^
 -DENABLE_PROFILING=%ENABLE_PROFILING%^
 -DENABLE_LOGGING=%ENABLE_LOGGING%^
 -DGUI_USE_IMGUI=%GUI_USE_IMGUI%^
 -DBUILD_EDITOR=%BUILD_EDITOR%^
 -B %BUILD_FOLDER%

cmake --build %BUILD_FOLDER% -j %NUMBER_OF_PROCESSORS% --target=install --config=%BUILD_TYPE%

pause