# CMAKE STUFF, YOU MAY NOT EVEN NEED THEM

# Build type categories: 
# Release
# RelWithDebInfo (Recommended when developing)
# Debug
# MinSizeRel
BUILD_TYPE=Release
BUILD_DIR=build
ENGINE_INSTALL_DIR=bin

STATIC_STD=1
USE_OPENGL=1
USE_VULKAN=1
ENABLE_PROFILING=0
ENABLE_LOGGING=1
GUI_USE_IMGUI=1
BUILD_EDITOR=1

# You don't have to change these
BUILD_FOLDER=$BUILD_DIR/$BUILD_TYPE
INSTALL_PREFIX=$ENGINE_INSTALL_DIR/$BUILD_TYPE

#Configure cmake
cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE \
-DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX \
-DSTATIC_STD=$STATIC_STD \
-DUSE_OPENGL=$USE_OPENGL \
-DUSE_VULKAN=$USE_VULKAN \
-DENABLE_PROFILING=$ENABLE_PROFILING \
-DENABLE_LOGGING=$ENABLE_LOGGING \
-DGUI_USE_IMGUI=$GUI_USE_IMGUI \
-DBUILD_EDITOR=$BUILD_EDITOR \
-B $BUILD_FOLDER

cmake --build $BUILD_FOLDER -j $(nproc) --target=install --config=$BUILD_TYPE