#pragma once

#ifndef POLOS_ENGINE_ENGINECONFIG_H_
#define POLOS_ENGINE_ENGINECONFIG_H_

#define MAX_ENTITY_COUNT_IN_SCENE 256
#define MAX_COMPONENT_COUNT_FOR_ENTITY 16

#endif /* POLOS_ENGINE_ENGINECONFIG_H_ */