#pragma once

#include "polos/platform/platform_detection.h"

#ifdef ENABLE_PROFILING
//// IMPLEMENTATIONS
#	if defined(POLOS_WIN) || defined(POLOS_LINUX)
#	include <optick.h>
#		define BEGIN_PROFILING_IMPL()               OPTICK_START_CAPTURE()
#		define STOP_PROFILING_IMPL()                OPTICK_STOP_CAPTURE()
#		define SAVE_PROFILING_IMPL(...)             OPTICK_SAVE_CAPTURE(__VA_ARGS__)
#		define PROFILE_SCOPE_IMPL(SCOPE_NAME)       OPTICK_EVENT(SCOPE_NAME)
#		define PROFILE_FRAME_IMPL(FRAME_NAME, ...)  OPTICK_FRAME(FRAME_NAME, __VA_ARGS__)
#		define PROFILE_THREAD_IMPL(THREAD_NAME)     OPTICK_THREAD(THREAD_NAME)
#		define PROFILE_FUNC_IMPL(...)               OPTICK_EVENT(__VA_ARGS__)
#		define PROFILE_TAG_IMPL(TAG_NAME, ...)      OPTICK_TAG(TAG_NAME, __VA_ARGS__)
#	elif defined(POLOS_MACOS)
#	include <optick.h>
#		define BEGIN_PROFILING_IMPL()               OPTICK_START_CAPTURE()
#		define STOP_PROFILING_IMPL()                OPTICK_STOP_CAPTURE()
#		define SAVE_PROFILING_IMPL(...)             OPTICK_SAVE_CAPTURE(__VA_ARGS__)
#		define PROFILE_SCOPE_IMPL(SCOPE_NAME)       OPTICK_EVENT(SCOPE_NAME)
#		define PROFILE_FRAME_IMPL(FRAME_NAME, ...)  OPTICK_FRAME(FRAME_NAME, __VA_ARGS__)
#		define PROFILE_THREAD_IMPL(THREAD_NAME)     OPTICK_THREAD(THREAD_NAME)
#		define PROFILE_FUNC_IMPL(...)               OPTICK_EVENT(__VA_ARGS__)
#		define PROFILE_TAG_IMPL(TAG_NAME, ...)      OPTICK_TAG(TAG_NAME, __VA_ARGS__)
#endif

/// Macros to use

#	define BEGIN_PROFILING()				BEGIN_PROFILING_IMPL()
#	define STOP_PROFILING()					STOP_PROFILING_IMPL()
#	define SAVE_PROFILING(...)				SAVE_PROFILING_IMPL(__VA_ARGS__)
#	define PROFILE_SCOPE(SCOPE_NAME)		PROFILE_SCOPE_IMPL(SCOPE_NAME)
#	define PROFILE_FRAME(FRAME_NAME, ...)	PROFILE_FRAME_IMPL(FRAME_NAME, ..)
#	define PROFILE_THREAD(THREAD_NAME)		PROFILE_THREAD_IMPL(THREAD_NAME)
#	define PROFILE_FUNC(...)				PROFILE_FUNC_IMPL(__VA_ARGS__)
#	define PROFILE_TAG(TAG_NAME, ...)		PROFILE_TAG_IMPL(TAG_NAME, __VA_ARGS__)
#else
#	define BEGIN_PROFILING()
#	define STOP_PROFILING()
#	define SAVE_PROFILING(...)
#	define PROFILE_SCOPE(SCOPE_NAME)
#	define PROFILE_FRAME(FRAME_NAME, ...)
#	define PROFILE_THREAD(THREAD_NAME)
#	define PROFILE_FUNC(...)
#	define PROFILE_TAG(TAG_NAME, ...)
#endif
