function (CheckConfigurationExist CONFIG_TYPE out_DOES_EXIST)
    string(TOLOWER ${CONFIG_TYPE} LOWER_CONFIG_TYPE)
    set(BUILD_DIR "${CMAKE_SOURCE_DIR}/out/build/win-${LOWER_CONFIG_TYPE}")
    if(EXISTS "${BUILD_DIR}/CMakeCache.txt")
        file(READ "${BUILD_DIR}/CMakeCache.txt" CACHE_CONTENT)
        if(CACHE_CONTENT MATCHES "CMAKE_BUILD_TYPE:STRING=${CONFIG_TYPE}")
            set(${out_DOES_EXIST} TRUE PARENT_SCOPE)
        else()
            set(${out_DOES_EXIST} FALSE PARENT_SCOPE)
        endif()
    else()
        set(${out_DOES_EXIST} FALSE PARENT_SCOPE)
    endif()
endfunction()
